### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by nguyenhiepvn** [nguyenhiepvn/protospace-41261#1]
#URL
https://protospace-41261.onrender.com/

**Comment by Katsuno0814** [comment]
@nguyenhiepvn さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
ユーザー管理機能

- [ ] プロフィールが必須であること
ユーザーの新規登録には、プロフィールを必須としましょう！
現在のユーザー新規登録ではプロフィールが空でも登録できてしまいます。

- [ ] ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること

ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されるよう実装しましょう。
現在トップページに「こんにちは、〇〇」と表示されております。名前の最後にさんが付くように修正しましょう！

ユーザー詳細機能

- [ ] ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること

1. ログイン状態のトップページで表示されております「こんにちは、〇〇さん」の箇所をクリックしてもユーザーマイページへ遷移できません、修正お願いいたします。

2. ログアウトの状態にでユーザーの詳細ページへ遷移しようとするとログイン画面へ遷移してしまいます。ユーザー詳細ページへと遷移できる様に修正お願いします！

- [ ] ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること
ユーザー詳細ページにて、下図の赤枠箇所がデフォルトの表示になっております、こちらユーザー詳細ページに紐づくユーザー名が表示される様にしましょう！
![スクリーンショット 2024-07-12 13 33 13](https://github.com/user-attachments/assets/ddae34b4-55f6-4de6-94f7-2357daee893e)

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたらProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。

**Comment by nguyenhiepvn** [comment]
@Katsuno0814  さん、お疲れ様です。
バグが多くてすみませんでした。先生、ご指摘いただきありがとうございました。
どうぞよろしくお願いいたします。

**Comment by Katsuno0814** [comment]
@nguyenhiepvn さん、ご提出ありがとうございます‼︎
修正いただきありがとうございます。
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

**Comment by nguyenhiepvn** [comment]
@Katsuno0814 さん、お疲れ様です。
ありがとうございました。
